Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeTable.Data;
using EmployeeTable.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeTable.Controllers
{
    public class DepartmentsController : Controller
    {
        private readonly EmployeeTableContext _context;

        public DepartmentsController(EmployeeTableContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
            return View(await _context.Departments.ToListAsync());
        }


        // GET: Departments/Create
        public IActionResult Create()
        {
            return PartialView("_CreatePartial");
        }

        // POST: Departments/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] Department department)
        {
            if(DepartmentNameInUse(department.Name))
            {
                ModelState.AddModelError("Name", "Департамент с таким названием уже существует");
            }
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
            }
            return PartialView("_CreatePartial", department);
        }


        // POST: Departments/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] Department department)
        {
            if (id != department.ID)
            {
                return NotFound();
            }
            if (DepartmentNameInUse(department.Name))
            {
                ModelState.AddModelError("Name", "Департамент с таким названием уже существует");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Index));
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var Department = await _context.Departments.FindAsync(id);
            _context.Departments.Remove(Department);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(int id)
        {
            return _context.Departments.Any(e => e.ID == id);
        }
        
        private bool DepartmentNameInUse(string departmentName)
        {
            return departmentName!=null && _context.Departments.Any(d => d.Name == departmentName);
        }
    }
}

Controllers/EmployeePositionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeeTable.Data;
using EmployeeTable.Models;

namespace EmployeeTable.Controllers
{
    public class EmployeePositionsController : Controller
    {
        private readonly EmployeeTableContext _context;

        public EmployeePositionsController(EmployeeTableContext context)
        {
            _context = context;
        }

        // GET: EmployeePositions
        public async Task<IActionResult> Index()
        {
            return View(await _context.EmployeePositions.ToListAsync());
        }

        
        // GET: EmployeePositions/Create
        public IActionResult Create()
        {
            return PartialView("_CreatePartial");
        }

        // POST: EmployeePositions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] EmployeePosition employeePosition)
        {
            if (EmployeePositionNameInUse(employeePosition.Name))
            {
                ModelState.AddModelError("Name", "Такая должность уже существует");
            }
            if (ModelState.IsValid)
            {
                _context.Add(employeePosition);
                await _context.SaveChangesAsync();
            }
            return PartialView("_CreatePartial", employeePosition);
        }
               

        // POST: EmployeePositions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] EmployeePosition employeePosition)
        {
            if (id != employeePosition.ID)
            {
                return NotFound();
            }
            if (EmployeePositionNameInUse(employeePosition.Name))
            {
                ModelState.AddModelError("Name", "Такая должность уже существует");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employeePosition);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeePositionExists(employeePosition.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Index));
        }

        // POST: EmployeePositions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employeePosition = await _context.EmployeePositions.FindAsync(id);
            _context.EmployeePositions.Remove(employeePosition);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeePositionExists(int id)
        {
            return _context.EmployeePositions.Any(e => e.ID == id);
        }

        private bool EmployeePositionNameInUse(string positionName)
        {
            return positionName != null && _context.EmployeePositions.Any(d => d.Name == positionName);
        }
    }
}

Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EmployeeTable.Data;
using EmployeeTable.Models;
using System.Diagnostics;

namespace EmployeeTable.Controllers
{
    public class EmployeesController : Controller
    {
        private readonly EmployeeTableContext _context;

        public EmployeesController(EmployeeTableContext context)
        {
            _context = context;
        }
		
		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            var employeeTableContext = _context.Employees
                .Include(e => e.Workplace)
                    .ThenInclude(w => w.Department)
                .Include(e => e.Workplace)
                    .ThenInclude(w => w.Organization)
                .Include(e => e.Position);
            ViewData["Position"] = new SelectList(_context.EmployeePositions, "ID", "Name");
            ViewData["Organization"] = new SelectList(_context.Organizations, "ID", "Name");
            ViewData["Department"] = new SelectList(_context.Departments, "ID", "Name");
            return View(await employeeTableContext.ToListAsync());
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            ViewData["Position"] = new SelectList(_context.EmployeePositions, "ID", "Name");
            ViewData["Organization"] = new SelectList(_context.Organizations, "ID", "Name");
            ViewData["Department"] = new SelectList(_context.Departments, "ID", "Name");
            return View();
        }

        // POST: Employees/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Surname,Name,Otch,Phone,Email,PositionID, DepartmentID, OrganizationID")] EmployeeWorkplaceViewModel employeeViewModel)
        {
            if (ModelState.IsValid)
            {
                Workplace workplace = FindWorkplaceOrCreateNew(employeeViewModel.DepartmentID, employeeViewModel.OrganizationID);              
                _context.Add(employeeViewModel.GetEmployee(workplace.ID));
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Position"] = new SelectList(_context.EmployeePositions, "ID", "Name", employeeViewModel.PositionID);
            ViewData["Organization"] = new SelectList(_context.Organizations, "ID", "Name", employeeViewModel.OrganizationID);
            ViewData["Department"] = new SelectList(_context.Departments, "ID", "Name", employeeViewModel.DepartmentID);

            return View(employeeViewModel);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .Include(e => e.Workplace)
                .SingleOrDefaultAsync(e => e.ID == id);
            if (employee == null)
            {
                return NotFound();
            }
            ViewData["Position"] = new SelectList(_context.EmployeePositions, "ID", "Name", employee.PositionID);
            ViewData["Organization"] = new SelectList(_context.Organizations, "ID", "Name", employee.Workplace.OrganizationID);
            ViewData["Department"] = new SelectList(_context.Departments, "ID", "Name", employee.Workplace.DepartmentID);

            return View(new EmployeeWorkplaceViewModel(employee));
        }

        // POST: Employees/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Surname,Name,Otch,Phone,Email,PositionID, DepartmentID, OrganizationID")] EmployeeWorkplaceViewModel employeeViewModel)
        {
            if (id != employeeViewModel.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                Workplace workplace = FindWorkplaceOrCreateNew(employeeViewModel.DepartmentID, employeeViewModel.OrganizationID);
                try
                {
                    _context.Update(employeeViewModel.GetEmployee(workplace.ID));
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeeExists(employeeViewModel.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Position"] = new SelectList(_context.EmployeePositions, "ID", "Name", employeeViewModel.PositionID);
            ViewData["Organization"] = new SelectList(_context.Organizations, "ID", "Name", employeeViewModel.OrganizationID);
            ViewData["Department"] = new SelectList(_context.Departments, "ID", "Name", employeeViewModel.DepartmentID);
            return View(employeeViewModel);
        }

        
        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employee = await _context.Employees.FindAsync(id);
            _context.Employees.Remove(employee);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeeExists(int id)
        {
            return _context.Employees.Any(e => e.ID == id);
        }

        private Workplace FindWorkplaceOrCreateNew(int departmentID, int organizationID)
        {
            Workplace workplace = _context.Workplace
                    .Where(w => w.DepartmentID == departmentID && w.OrganizationID == organizationID)
                    .SingleOrDefault();
            if (workplace == null)
            {
                workplace = new Workplace()
                {
                    OrganizationID = organizationID,
                    DepartmentID = departmentID
                };
                _context.Add(workplace);
                _context.SaveChanges();
            }
            return workplace;
        }
    }
}

Controllers/OrganizationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EmployeeTable.Data;
using EmployeeTable.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace EmployeeTable.Controllers
{
    public class OrganizationsController : Controller
    {
        private readonly EmployeeTableContext _context;

        public OrganizationsController(EmployeeTableContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.Organizations.ToListAsync());
        }

        // GET: Organizations/Create
        public IActionResult Create()
        {
            return PartialView("_CreatePartial");
        }

        // POST: Organizations/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Name")] Organization organization)
        {
            if(OrganizationNameInUse(organization.Name))
            {
                ModelState.AddModelError("Name", "Организация с таким именем уже существует");
            }
            if (ModelState.IsValid)
            {
                _context.Add(organization);
                await _context.SaveChangesAsync();
            }
            return PartialView("_CreatePartial", organization);
        }


        // POST: Organizations/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Name")] Organization organization)
        {
            if (id != organization.ID)
            {
                return NotFound();
            }
            if (OrganizationNameInUse(organization.Name))
            {
                ModelState.AddModelError("Name", "Организация с таким именем уже существует");
            }
            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(organization);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrganizationExists(organization.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nameof(Index));
        }

        // POST: Organizations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var organization = await _context.Organizations.FindAsync(id);
            _context.Organizations.Remove(organization);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrganizationExists(int id)
        {
            return _context.Organizations.Any(e => e.ID == id);
        }

        private bool OrganizationNameInUse(string organizationName)
        {
            return organizationName != null && _context.Organizations.Any(d => d.Name == organizationName);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Сотрудники клиентов</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Employees" asp-action="Index">Сотрудники клиентов</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Главная</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Organizations" asp-action="Index">Организации</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeePositions" asp-action="Index">Должности</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Департаменты</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid">
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container-fluid">

        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>